package ktapi.kotlinsecurity.domain.exception

class DataAlreadyExistsException : Exception {
    constructor(message: String) : super(message)
    constructor(message: String, cause: Throwable) : super(message, cause)
    constructor(cause: Throwable) : super(cause)
}